core/urls.py
from django.urls import path
from core.views import register, user_logout, add_donation, user_account, activate, contact_form, create_donation, \
    form_confirmation, donation_is_taken, HomeView
from django.contrib.auth.views import LoginView

app_name = 'core'

urlpatterns = [


    path('register/', register, name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),


    path('activate/<uidb64>/<token>/', activate, name='activate'),

    path('contact/', contact_form, name='contact_form'),
    path('', HomeView.as_view(), name='home'),
    path('donation/', add_donation, name='donation'),
    path('create_donation/', create_donation, name='create_donation'),
    path('form_confirmation/', form_confirmation, name="form_confirmation"),
    path('profile/', user_account, name='profile'),
    path('taken-item/<id>/', donation_is_taken, name="taken"),
]

portfolioLab/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView
from django.urls import path, include

urlpatterns = [
    path('password_change/', PasswordChangeView.as_view(template_name='core/password_change.html'), name='password_change'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls', namespace='core')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from portfolioLab import settings
from .managers import CustomUserManager


class CustomUser(AbstractUser):
    username = None
    email = models.EmailField('email address', unique=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Category(models.Model):
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.name


ORG_TYPES = (
    ('Fundacja', 'Fundacja'),
    ('NGOs', 'NGOs'),
    ('Zbiórka', 'Zbiórka lokalna')
)


class Institution(models.Model):
    name = models.CharField(max_length=100, null=False)
    description = models.TextField()
    type = models.CharField(choices=ORG_TYPES,
                            default='Fundacja', max_length=15)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Donation(models.Model):
    quantity = models.PositiveIntegerField(default=1)
    categories = models.ManyToManyField(Category)
    institution = models.ForeignKey(Institution, on_delete=models.CASCADE)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    zip_code = models.CharField(max_length=6)
    pick_up_date = models.DateField()
    pick_up_time = models.TimeField()
    pick_up_comment = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, default=None)
    is_taken = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.quantity} dla {self.institution}'

    def get_taken_item_url(self):
        return reverse("core:taken", kwargs={
            'id': self.id
        })

core/forms.py
from django import forms

from core.models import CustomUser, Donation


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Hasło',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(label='Powtórz Hasło',
                                widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email')

    def clean_password2(self, *args, **kwargs):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Hasła nie są takie same')
        elif len(cd['password']) < 8:
            raise forms.ValidationError("Hasło musi mieć przynajmniej 8 znaków.")
        elif not any(c.isdigit() for c in cd['password']):
            raise forms.ValidationError("Hasło musi zawierać przynajmniej jedną cyfrę.")
        return super(UserRegistrationForm, self).clean(*args, **kwargs)


class Donator(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'email')


class ContactForm(forms.Form):
    name = forms.CharField(max_length=23, required=True)
    surname = forms.CharField(max_length=33, required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get("name")
        surname = cleaned_data.get("surname")
        message = cleaned_data.get("message")
        if not name and surname and message:
            raise forms.ValidationError(
                'All fields required')


class DonationForm(forms.ModelForm):
    class Meta:
        model = Donation
        fields = ("quantity", "categories", "institution", "address", "phone_number", "zip_code",
                  "pick_up_date", "pick_up_time", "pick_up_comment", "is_taken")

core/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail, EmailMessage
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView

from core.forms import UserRegistrationForm, Donator, ContactForm, DonationForm
from .models import Institution, Category, CustomUser, Donation
from .tokens import account_activation_token


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(
                user_form.cleaned_data['password'])
            new_user.save()
            # Sending an email with registration confirmation
            current_site = get_current_site(request)
            mail_subject = 'Activate your account on "Oddam w Dobre Ręce"'
            message = render_to_string('core/acc_active_email.html', {
                'user': new_user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
                'token': account_activation_token.make_token(new_user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            messages.success(request, "Hello, we have just send you an email with an activation link")
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
        else:
            pass
    else:
        user_form = UserRegistrationForm()
    return render(request,
                  'core/register.html',
                  {'user_form': user_form})


def activate(request, uidb64, token):
    # Registration confirmation with token
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = CustomUser.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, CustomUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        messages.success(request, 'Thank you for your confirmation. Now you can sign in')
        return redirect('core:login')
    else:
        return HttpResponse('Activation link invalid')


def user_logout(request):

    logout(request)
    return redirect('core:home')


class HomeView(TemplateView):
    template_name = 'core/index.html'


def add_donation(request):

    form = DonationForm()
    categories = Category.objects.all()
    institution_to_get = Institution.objects.all()

    return render(request, 'core/form.html', {'form': form, 'categories': categories,
                                              'institution_to_get': institution_to_get})


def create_donation(request):

    if request.is_ajax() and request.method == 'POST':

        form = DonationForm(request.POST)
        categories_ids = request.POST.getlist('categories')
        categories = Category.objects.filter(id__in=categories_ids)

        if form.is_valid():
            donation = form.save(commit=False)
            donation.user = request.user
            donation.save()
            donation.categories.set(categories)
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'error': form.errors})


def form_confirmation(request):
    return render(request, 'core/form-confirmation.html', {})


def user_account(request):
    user = request.user
    user_detail_form = Donator(instance=user)
    user_donations = Donation.objects.filter(user=user)

    taken = user_donations.filter(is_taken=True).order_by('pick_up_date')
    not_taken = user_donations.filter(is_taken=False).order_by('pick_up_date')

    if request.method == 'POST':
        user_detail_form = Donator(request.POST, instance=user)
        if user_detail_form.is_valid():
            user_detail_form.save()
            messages.success(request, "Changes saved successfully!")

    return render(request, 'core/account.html', {'form': user_detail_form, 'user_donations': user_donations,
                                                 "taken": taken, "not_taken": not_taken})


def donation_is_taken(request, pk):
    # changing the donation status - from active to taken (collected by courier)
    donation = Donation.objects.get(id=pk)
    donation.is_taken = True
    donation.save()
    return redirect('core:profile')


def contact_form(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            superusers_emails = CustomUser.objects.filter(is_superuser=True).values_list('email', flat=True)
            subject = f"Contact form from: {cd['name']} {cd['surname']}"
            send_mail(subject, cd['message'], settings.EMAIL_HOST_USER,
                      superusers_emails)
            return render(request, 'core/form-confirmation.html')
        else:
            messages.warning(request, 'Got error while sending a contact form. All fields required.')
    return render(request, 'core/base.html', {'form': form})

core/templates/core/acc_active_email.html
{% autoescape off %}
Cześć {{ user.first_name|title }}!,
Kliknij w poniższy link aby potwierdzić rejestrację ,http://{{ domain }}{% url 'core:activate' uidb64=uid token=token %}
    Pozdrawiamy,
    Zespół Oddam w dobre ręce
{% endautoescape %}

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pl">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href={% static "css/style.css" %} />
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
  </script>
      <script src="https://kit.fontawesome.com/31e8b05626.js" crossorigin="anonymous"></script>
  </head>
<body>

{% block content %}

{% endblock %}

<footer>
      <div id="contact" class="contact">
        <h2>Skontaktuj się z nami</h2>
        <h3>Formularz kontaktowy</h3>
        <form class="form--contact" method="post" action="{% url 'core:contact_form' %}">
            {% csrf_token %}
            <div class="form-group form-group--50"><input type="text" name="name" placeholder="Imię"/></div>
            <div class="form-group form-group--50"><input type="text" name="surname" placeholder="Nazwisko"/></div>
            <div class="form-group"><textarea name="message" placeholder="Wiadomość" rows="1"></textarea></div>
          <button class="btn" type="submit">Wyślij</button>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </form>
      </div>
      <div class="bottom-line">
        <span class="bottom-line--copy">Copyright &copy; 2018</span>
        <div class="bottom-line--icons">
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-facebook.svg' %}"
          /></a>
          <a href="#" class="btn btn--small"
            ><img src="{% static 'images/icon-instagram.svg' %}"
          /></a>
        </div>
      </div>
    </footer>


</body>
  <script src="{% static 'js/app.js' %}"></script>
</html>

core/templates/core/form-confirmation.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<header class="header--form-page">

    {% include 'core/navbar.html' %}

      <div class="slogan container container--90">
          <h2>
            Dziękujemy za przesłanie formularza. Na maila prześlemy wszelkie
            informacje o odbiorze. Wejdź na swój <a style="color: blue; text-decoration: underline" href="{% url 'core:profile' %}">profil</a>
              i sprawdź podsumowanie przekazanych darów!
          </h2>
      </div>
</header>
{% endblock %}

core/templates/core/form.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
    <header class="header--form-page">

{% include 'core/navbar.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Oddaj rzeczy, których już nie chcesz<br />
            <span class="uppercase">potrzebującym</span>
          </h1>

          <div class="slogan--steps">
            <div class="slogan--steps-title">Wystarczą 4 proste kroki:</div>
            <ul class="slogan--steps-boxes">
              <li>
                <div><em>1</em><span>Wybierz rzeczy</span></div>
              </li>
              <li>
                <div><em>2</em><span>Spakuj je w worki</span></div>
              </li>
              <li>
                <div><em>3</em><span>Wybierz fundację</span></div>
              </li>
              <li>
                <div><em>4</em><span>Zamów kuriera</span></div>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>

    <section class="form--steps">
      <div class="form--steps-instructions">
        <div class="form--steps-container">
          <h3>Ważne!</h3>
          <p data-step="1" class="active">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="2">
            Uzupełnij szczegóły dotyczące Twoich rzeczy. Dzięki temu będziemy
            wiedzieć komu najlepiej je przekazać.
          </p>
          <p data-step="3">
           Wybierz jedną, do
            której trafi Twoja przesyłka.
          </p>
          <p data-step="4">Podaj adres oraz termin odbioru rzeczy.</p>
        </div>
      </div>

      <div class="form--steps-container">
        <div class="form--steps-counter">Krok <span>1</span>/5</div>

      {% if form.errors %}
        <p>Coś poszło nie tak. Spróbuj wypełnić formularz jeszcze raz</p>
        {% endif %}
        <form id="donation_form" action="{% url 'core:create_donation' %}" method="post">
          <!-- STEP 1: class .active is switching steps -->
        {% csrf_token %}
          <div data-step="1" class="active">
            <h3>Zaznacz co chcesz oddać:</h3>
              {% for category in categories %}
            <div class="form-group form-group--checkbox">
              <label>
                <input
                        id="categories"
                  type="checkbox"
                  name="categories"
                  value="{{ category.id }}"
                />
                <span class="checkbox"></span>
                <span  class="description"
                  >{{ category.name }}</span
                >
              </label>
            </div>
            {% endfor %}

            <div class="form-group form-group--buttons">
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 2 -->
          <div data-step="2">
            <h3>Podaj liczbę 60l worków, w które spakowałeś/aś rzeczy:</h3>


            <div class="form-group form-group--inline">
              <label> Liczba 60l worków: </label>
                {{ form.quantity }}
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 4 -->
          <div data-step="3">
            <h3>Wybierz organizacje, której chcesz pomóc:</h3>
    {% for institution in institution_to_get %}
            <div class="form-group form-group--checkbox">
              <label>
                <input type="radio" name="institution" value="{{ institution.id }}" />
                <span class="checkbox radio"></span>
                <span class="description">
                  <div id="institution" class="title">{{ institution.name}}</div>
                  <div class="subtitle">
                    {{ institution.description}}
                  </div>
                </span>
              </label>
            </div>
    {% endfor %}
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 5 -->
          <div data-step="4">
            <h3>Podaj adres oraz termin odbioru rzecz przez kuriera:</h3>

            <div class="form-section form-section--columns">
              <div class="form-section--column">
                <h4>Adres odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Ulica </label>
                    {{ form.address }}
                </div>

{#                <div class="form-group form-group--inline">#}
{#                  <label> Miasto <input type="text" name="city" /> </label>#}
{#                </div>#}

                <div class="form-group form-group--inline">
                  <label>
                    Kod pocztowy
                  </label>
                    {{ form.zip_code }}
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Numer telefonu
                  </label>
                    {{ form.phone_number }}
                </div>
              </div>

              <div class="form-section--column">
                <h4>Termin odbioru</h4>
                <div class="form-group form-group--inline">
                  <label> Data</label>
                    {{ form.pick_up_date }}
                </div>

                <div class="form-group form-group--inline">
                  <label> Godzina </label>
                    {{ form.pick_up_time }}
                </div>

                <div class="form-group form-group--inline">
                  <label>
                    Uwagi dla kuriera
                  </label>
                    {{ form.pick_up_comment }}
                </div>
              </div>
            </div>
            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="button" class="btn next-step">Dalej</button>
            </div>
          </div>

          <!-- STEP 6 -->
          <div data-step="5">
            <h3>Podsumowanie Twojej darowizny</h3>

            <div class="summary">
              <div class="form-section">
                <h4>Oddajesz:</h4>
                <ul>
                  <li>
                    <span class="icon icon-bag"></span>
                    <span class="summary--text" id="span_quantity"
                      > </span
                    >
                  </li>

                  <li>
                    <span class="icon icon-hand"></span>
                    <span class="summary--text" id="span_institution"
                      ></span
                    >
                  </li>
                </ul>
              </div>

              <div class="form-section form-section--columns">
                <div class="form-section--column">
                  <h4>Adres odbioru:</h4>
                  <ul>
                    <li id="adres">Prosta 51</li>
                    <li id="li_zip">99-098</li>
                    <li id="li_phone">123 456 789</li>
                  </ul>
                </div>

                <div class="form-section--column">
                  <h4>Termin odbioru:</h4>
                  <ul>
                    <li id="li_date">13/12/2018</li>
                    <li id="li_time">15:40</li>
                    <li id="li_comment">Brak uwag</li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="form-group form-group--buttons">
              <button type="button" class="btn prev-step">Wstecz</button>
              <button type="submit" class="btn">Potwierdzam</button>
            </div>
          </div>
        </form>
      </div>
    </section>


{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load core_tags %}
{% load static %}

{% block content %}

    <header class="header--main-page">

        {% include 'core/navbar.html' %}

      <div class="slogan container container--90">
        <div class="slogan--item">
          <h1>
            Zacznij pomagać!<br />
            Oddaj niechciane rzeczy w zaufane ręce
          </h1>
        </div>
      </div>
    </header>

    <section id="stats" class="stats">
      <div class="container container--85">
        <div class="stats--item">
          <em>{% get_total_bags_num %}</em>
          <h3>Oddanych worków</h3>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius est beatae, quod accusamus illum tempora!</p>
        </div>

        <div class="stats--item">
          <em>{% total_organizations %}</em>
          <h3>Wspartych organizacji</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laboriosam magnam, sint nihil cupiditate quas quam.</p>
        </div>

      </div>
    </section>

    <section id="steps" class="steps">
      <h2>Wystarczą 4 proste kroki</h2>

      <div class="steps--container">
        <div class="steps--item">
          <span class="icon icon--hands"></span>
          <h3>Wybierz rzeczy</h3>
          <p>ubrania, zabawki, sprzęt i inne</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--arrow"></span>
          <h3>Spakuj je</h3>
          <p>skorzystaj z worków na śmieci</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--glasses"></span>
          <h3>Zdecyduj komu chcesz pomóc</h3>
          <p>wybierz zaufane miejsce</p>
        </div>
        <div class="steps--item">
          <span class="icon icon--courier"></span>
          <h3>Zamów kuriera</h3>
          <p>kurier przyjedzie w dogodnym terminie</p>
        </div>
      </div>

      <a href="{% url 'core:register' %}"  class="btn btn--large">Załóż konto</a>
    </section>

    <section id="about-us" class="about-us">
      <div class="about-us--text">
        <h2>O nas</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas vitae animi rem pariatur incidunt libero optio esse quisquam illo omnis.</p>
        <img src="{%static 'images/signature.svg'%}" class="about-us--text-signature" alt="Signature" />
      </div>
      <div class="about-us--image"><img src="{%static 'images/about-us.jpg'%}" alt="People in circle" /></div>
    </section>

     <section id="help" class="help">
      <h2>Komu pomagamy?</h2>

      <ul class="help--buttons">
        <li data-id="1"><a href="#" class="btn btn--without-border active">Fundacjom</a></li>
        <li data-id="2"><a href="#" class="btn btn--without-border">Organizacjom pozarządowym</a></li>
        <li data-id="3"><a href="#" class="btn btn--without-border">Lokalnym zbiórkom</a></li>
      </ul>

      <!-- SLIDE 1 -->
      <div class="help--slides active" data-id="1">
        <p>W naszej bazie znajdziesz listę zweryfikowanych Fundacji, z którymi współpracujemy. Możesz sprawdzić czym się zajmują, komu pomagają i czego potrzebują.</p>
          {% show_fundations as fundations %}
          {% for fund in fundations %}
        <ul class="help--slides-items">

            <li>
            <div class="col">
              <div class="title">{{ fund.name }}</div>
              <div class="subtitle">Cele i misja: {{ fund.description|truncatewords:15 }}...</div>
            </div>
            <div class="col"><div class="text">ubrania, jedzenie, sprzęt AGD, meble, zabawki</div></div>
          </li>
        </ul>
{% endfor %}
      </div>


      <!-- SLIDE 2 -->
      <div class="help--slides" data-id="2">
        <p>
          Lorem ipsum dolor, sit amet consectetur adipisicing elit. Hic officiis mollitia dolor, neque aspernatur accusamus debitis. Ducimus, officia. Quia, sunt illum! Non iste placeat ab ipsum alias
          quos suscipit corporis!
        </p>
          {% show_ngos as ngos %}
          {% for ngo in ngos %}
        <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ ngo.name }}</div>
              <div class="subtitle">Cele i misja: {{ ngo.description|truncatewords:15 }}...</div>
            </div>
            <div class="col"><div class="text">ubrania, jedzenie, sprzęt AGD, meble, zabawki</div></div>
          </li>
        </ul>
{% endfor %}
      </div>

      <!-- SLIDE 3 -->
      <div class="help--slides" data-id="3">
        <p>Lorem ipsum dolor sit amet, his ocurreret persequeris ea, ad utinam laudem duo. Verterem adipisci partiendo eos ne, ea his reque quaeque recteque, ne quo lobortis intellegam.</p>
        {% show_local_raise as raises %}
          {% for raise in raises %}
          <ul class="help--slides-items">
          <li>
            <div class="col">
              <div class="title">{{ raise.name }}</div>
              <div class="subtitle">Cele i misja: {{ raise.description|truncatewords:15 }}...</div>
            </div>

            <div class="col"><div class="text">Lorem ipsum dolor sit amet consectetur adipisicing elit.</div></div>
          </li>
        </ul>
{% endfor %}

      </div>
    </section>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <header>
        {% include 'core/navbar.html' %}
    </header>

    <section class="login-page">
      <h2>Zaloguj się</h2>
      <form method="POST" action="">
         <div class="form-group">
             {% csrf_token %}
             {{ form.as_p }}
         <a href="#" class="btn btn--small btn--without-border reset-password">Przypomnij hasło</a>
             <br>
             {% for message in messages %}
                 <p> <strong style="color: green">{{ message }}</strong> </p>
             {% endfor %}
        </div>

        <div class="form-group form-group--buttons">
          <a href="{% url 'core:register' %}" class="btn btn--without-border">Załóż konto</a>
            <button class="btn" type="submit">Zaloguj się</button>
        </div>
      </form>
    </section>
{% endblock %}

core/templates/core/navbar.html
<nav class="container container--70">
    {% if request.user.is_authenticated %}
        <ul class="nav--actions">
          <li class="logged-user">
            Witaj {{ request.user.first_name }}
            <ul class="dropdown">
              <li><a href="{% url 'core:profile' %}">Profil</a></li>
              <li><a href="{% url 'password_change' %}">Ustawienia</a></li>
              <li><a href="{% url 'core:logout' %}">Wyloguj</a></li>
                {% if request.user.is_staff %}
                <li><a href="/admin/">Admin</a> </li>
                {% endif %}
            </ul>
          </li>
        </ul>
    {% else %}
        <ul class="nav--actions">
          <li><a href="{% url 'core:login' %}" class="btn btn--small btn--without-border">Zaloguj</a></li>
          <li><a href="{% url 'core:register' %}" class="btn btn--small btn--highlighted">Załóż konto</a></li>
        </ul>
   {% endif %}
        <ul>
          <li><a href="{% url 'core:home' %}" class="btn btn--without-border active">Start</a></li>
          <li><a href="{% url 'core:home' %}#steps" class="btn btn--without-border">O co chodzi?</a></li>
          <li><a href="{% url 'core:home' %}#about-us" class="btn btn--without-border">O nas</a></li>
          <li><a href="{% url 'core:home' %}#help" class="btn btn--without-border">Fundacje i organizacje</a></li>
            {% if request.user.is_authenticated %}
                <li><a href="{% url 'core:donation'%}" class="btn btn--without-border">Przekaż dary</a></li>
            {% endif %}
            <li><a href="{% url 'core:home' %}#contact" class="btn btn--without-border">Kontakt</a></li>
        </ul>

      </nav>

core/templates/core/password_change.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
    <header>
        {% include 'core/navbar.html' %}
    </header>


<section class="login-page">
      <h2>Zmiana hasła</h2>
    {% if validlink %}
    <p>Podaj dwukrotnie nowe hasło</p>
    <form method="POST" action="">
         <div class="form-group">
             {% csrf_token %}
             {{ form.as_p }}
             <br>
        </div>

        <div class="form-group form-group--buttons">
            <button class="btn" type="submit">Zmień hasło</button>
        </div>
      </form>
{% else %}
<p>Łącze resetujące hasło jest nieprawidłowe. Musisz rozpocząć od nowa</p>
{% endif %}
</section>
{% endblock %}

core/templates/core/password_change_done.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}
<header class="header--form-page">

    {% include 'core/navbar.html' %}

      <div class="slogan container container--90">
          <h2>
            Hasło zostało zmienione. Możesz <a href="{% url 'login' %}">zalogować się</a> z nowym hasłem.
          </h2>
      </div>
</header>
{% endblock %}